# Generated by Django 4.2.23 on 2025-06-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Utenti",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Utente (Legacy)",
                "verbose_name_plural": "Utenti (Legacy)",
                "db_table": "Utenti",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Targa",
            fields=[
                (
                    "numero",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Numero Targa",
                    ),
                ),
                (
                    "dataEm",
                    models.DateField(db_column="dataEm", verbose_name="Data Emissione"),
                ),
            ],
            options={
                "verbose_name": "Targa",
                "verbose_name_plural": "Targhe",
                "db_table": "Targa",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="Veicolo",
            fields=[
                (
                    "telaio",
                    models.CharField(
                        help_text="Numero di telaio univoco del veicolo",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Numero Telaio",
                    ),
                ),
                ("marca", models.CharField(max_length=100, verbose_name="Marca")),
                ("modello", models.CharField(max_length=100, verbose_name="Modello")),
                (
                    "dataProd",
                    models.DateField(
                        db_column="dataProd", verbose_name="Data Produzione"
                    ),
                ),
            ],
            options={
                "verbose_name": "Veicolo",
                "verbose_name_plural": "Veicoli",
                "db_table": "Veicolo",
                "ordering": ["marca", "modello"],
            },
        ),
        migrations.CreateModel(
            name="Revisione",
            fields=[
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                (
                    "dataRev",
                    models.DateField(
                        db_column="dataRev", verbose_name="Data Revisione"
                    ),
                ),
                (
                    "esito",
                    models.CharField(
                        choices=[("positivo", "Positivo"), ("negativo", "Negativo")],
                        max_length=10,
                        verbose_name="Esito",
                    ),
                ),
                (
                    "motivazione",
                    models.TextField(
                        blank=True,
                        help_text="Obbligatoria per esito negativo, vuota per esito positivo",
                        null=True,
                        verbose_name="Motivazione",
                    ),
                ),
                (
                    "targa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sistema_gestione_veicoli.targa",
                        verbose_name="Targa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisione",
                "verbose_name_plural": "Revisioni",
                "db_table": "Revisione",
                "ordering": ["-dataRev"],
            },
        ),
        migrations.CreateModel(
            name="TargaRestituita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_res",
                    models.DateField(
                        db_column="dataRes", verbose_name="Data Restituzione"
                    ),
                ),
                (
                    "targa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sistema_gestione_veicoli.targa",
                        verbose_name="Targa",
                    ),
                ),
                (
                    "veicolo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sistema_gestione_veicoli.veicolo",
                        verbose_name="Veicolo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Targa Restituita",
                "verbose_name_plural": "Targhe Restituite",
                "db_table": "TargaRestituita",
                "ordering": ["-data_res"],
                "unique_together": {("targa", "veicolo", "data_res")},
            },
        ),
        migrations.CreateModel(
            name="TargaAttiva",
            fields=[
                (
                    "targa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="sistema_gestione_veicoli.targa",
                        verbose_name="Targa",
                    ),
                ),
                (
                    "veicolo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sistema_gestione_veicoli.veicolo",
                        verbose_name="Veicolo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Targa Attiva",
                "verbose_name_plural": "Targhe Attive",
                "db_table": "TargaAttiva",
            },
        ),
    ]
