# Generated by Django 5.2.3 on 2025-07-15 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Targa",
            fields=[
                (
                    "numero",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Numero Targa",
                    ),
                ),
                (
                    "dataEm",
                    models.DateField(db_column="dataEm", verbose_name="Data Emissione"),
                ),
            ],
            options={
                "verbose_name": "targa",
                "verbose_name_plural": "targhe",
                "db_table": "targa",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="Veicolo",
            fields=[
                (
                    "telaio",
                    models.CharField(
                        help_text="Numero di telaio univoco del veicolo",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Numero Telaio",
                    ),
                ),
                ("marca", models.CharField(max_length=100, verbose_name="marca")),
                ("modello", models.CharField(max_length=100, verbose_name="modello")),
                (
                    "dataProd",
                    models.DateField(
                        db_column="dataProd", verbose_name="dataProduzione"
                    ),
                ),
            ],
            options={
                "verbose_name": "veicolo",
                "verbose_name_plural": "veicoli",
                "db_table": "veicolo",
                "ordering": ["telaio"],
            },
        ),
        migrations.CreateModel(
            name="Revisione",
            fields=[
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                (
                    "dataRev",
                    models.DateField(db_column="dataRev", verbose_name="dataRevisione"),
                ),
                (
                    "esito",
                    models.CharField(
                        choices=[("positivo", "Positivo"), ("negativo", "Negativo")],
                        max_length=10,
                        verbose_name="esito",
                    ),
                ),
                (
                    "motivazione",
                    models.TextField(
                        blank=True,
                        help_text="Obbligatoria per esito negativo, vuota per esito positivo",
                        null=True,
                        verbose_name="motivazione",
                    ),
                ),
                (
                    "targa",
                    models.ForeignKey(
                        db_column="targa",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sistema_gestione_veicoli.targa",
                        verbose_name="targa",
                    ),
                ),
            ],
            options={
                "verbose_name": "revisione",
                "verbose_name_plural": "revisioni",
                "db_table": "revisione",
                "ordering": ["-dataRev"],
            },
        ),
        migrations.CreateModel(
            name="TargaAttiva",
            fields=[
                (
                    "targa",
                    models.OneToOneField(
                        db_column="targa",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="sistema_gestione_veicoli.targa",
                        verbose_name="targa",
                    ),
                ),
                (
                    "veicolo",
                    models.OneToOneField(
                        db_column="veicolo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sistema_gestione_veicoli.veicolo",
                        verbose_name="veicolo",
                    ),
                ),
            ],
            options={
                "verbose_name": "targa attiva",
                "verbose_name_plural": "targhe attive",
                "db_table": "targa_attiva",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TargaRestituita",
            fields=[
                (
                    "targa",
                    models.OneToOneField(
                        db_column="targa",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="sistema_gestione_veicoli.targa",
                        verbose_name="targa",
                    ),
                ),
                (
                    "dataRes",
                    models.DateField(
                        db_column="dataRes", verbose_name="Data Restituzione"
                    ),
                ),
                (
                    "veicolo",
                    models.OneToOneField(
                        db_column="veicolo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sistema_gestione_veicoli.veicolo",
                        verbose_name="veicolo",
                    ),
                ),
            ],
            options={
                "verbose_name": "targa restituita",
                "verbose_name_plural": "targhe restituite",
                "db_table": "targa_restituita",
                "managed": True,
            },
        ),
    ]
